env:
  global:
  - secure: Pub+0A1pN1RifBo091ipt0WUoatLxS0jc7ZappgoK4h2vghHdC0w90uxBiTCn4nCuSOnzeUB4oQ2qGVREMtrS4pa4p/LVkSSf1Qs207+Kj6os10B5+ecfNJ/r9kfG3+BddwJWTjYvKRy07lmGiSbfIS7GKOx3Zb8ymuul2Y3rH8=
  - secure: Vm1X+atKdU2AT44KdUD9t1GUaUY7xDCp4Nv/Ulggh4yPN3m/15vBZ2zFVvvuSePAvLLxS16dM46VC2jmGDo0PqCLTT/s+ZsQnQu6EwCfgxww2bakV22muCxcRo4PPJCm1qrLjNpKm0zOPBw85V9E/IRAZIvexQz7C31f/lkL/rk=
notifications:
  hipchat:
    rooms:
      secure: dtIZnyQ5l7HoMHAPYE/7EmZ5ic9/vJAzUjNWWPHqPjuUWuh2EYQhPaQGlN/lMrcEAg/vrDdwga/vR729TGCgE7fyiElE9oRC1A/7xwiW8bgdOzDLINkH2/QW8GfRS7J+rFN3iFxOw0jVKcynDC3dt46ZS24xaTcGz3/BDdS6E1k=
language: php
php:
- 5.4
- 5.5
- 5.6
before_script:
- |
  echo "apiKey: $API_KEY" > test_configuration.local.yml
script:
- mkdir -p build/logs
- composer install --dev --prefer-dist
- vendor/bin/phpunit -c ./phpunit.xml.dist --bootstrap ./tests/bootstrap.php --verbose
  --debug || exit 1
after_script:
- php vendor/bin/coveralls -v
